# Generated by Django 4.2.7 on 2024-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='notes',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
